//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestsEntities : DbContext
    {
        private static TestsEntities _context;
        public TestsEntities()
            : base("name=TestsEntities")
        {
        }

        public static TestsEntities GetContext()
        {
            if (_context == null)
            {
                _context = new TestsEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<questions_types> questions_types { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<test_answers> test_answers { get; set; }
        public virtual DbSet<test_results> test_results { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
